artifacts_root: artifacts

data_ingestion:
  root: artifacts/data_ingestion
  URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

