artifacts_root: artifacts

data_ingestion:
  root: artifacts/data_ingestion
  URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_checking:
  root: artifacts/data_checking
  status_file: artifacts/data_checking/status.txt
  required_files: ["train", "test", "validation"]


data_transformation:
  root: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
